package com.ddway.anagraficaBS.model.db.anagraficaBS;

// Generated Apr 17, 2014 2:09:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.stereotype.Service;

/**
 * DModelApplicativi generated by hbm2java
 */
@Service
public class DModelApplicativi implements java.io.Serializable {

	private Integer codiModelApplicativo;
	private String descModelApplicativo;
	private Date dataInizioValidita;
	private Date dataFineValidita;
	private Set<DServiziModel> DServiziModels = new HashSet<DServiziModel>(0);

	public DModelApplicativi() {
	}

	public DModelApplicativi(String descModelApplicativo,
			Date dataInizioValidita, Date dataFineValidita,
			Set<DServiziModel> DServiziModels) {
		this.descModelApplicativo = descModelApplicativo;
		this.dataInizioValidita = dataInizioValidita;
		this.dataFineValidita = dataFineValidita;
		this.DServiziModels = DServiziModels;
	}

	public Integer getCodiModelApplicativo() {
		return this.codiModelApplicativo;
	}

	public void setCodiModelApplicativo(Integer codiModelApplicativo) {
		this.codiModelApplicativo = codiModelApplicativo;
	}

	public String getDescModelApplicativo() {
		return this.descModelApplicativo;
	}

	public void setDescModelApplicativo(String descModelApplicativo) {
		this.descModelApplicativo = descModelApplicativo;
	}

	public Date getDataInizioValidita() {
		return this.dataInizioValidita;
	}

	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	public Date getDataFineValidita() {
		return this.dataFineValidita;
	}

	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	public Set<DServiziModel> getDServiziModels() {
		return this.DServiziModels;
	}

	public void setDServiziModels(Set<DServiziModel> DServiziModels) {
		this.DServiziModels = DServiziModels;
	}

}
