package com.ddway.anagraficaBS.model.db.anagraficaBS;

import java.math.BigDecimal;
import java.util.Date;

/**
 * DPesoBs generated by hbm2java
 */
public class DPesoBs implements java.io.Serializable {

	private DPesoBsId id;
	private BigDecimal misuPesoBs;
	private Date dataFineAssociazione;

	public DPesoBs() {
	}

	public DPesoBs(DPesoBsId id) {
		this.id = id;
	}

	public DPesoBs(DPesoBsId id, BigDecimal misuPesoBs,
			Date dataFineAssociazione) {
		this.id = id;
		this.misuPesoBs = misuPesoBs;
		this.dataFineAssociazione = dataFineAssociazione;
	}

	public DPesoBsId getId() {
		return this.id;
	}

	public void setId(DPesoBsId id) {
		this.id = id;
	}

	public BigDecimal getMisuPesoBs() {
		return this.misuPesoBs;
	}

	public void setMisuPesoBs(BigDecimal misuPesoBs) {
		this.misuPesoBs = misuPesoBs;
	}

	public Date getDataFineAssociazione() {
		return this.dataFineAssociazione;
	}

	public void setDataFineAssociazione(Date dataFineAssociazione) {
		this.dataFineAssociazione = dataFineAssociazione;
	}

}
