package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:01:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DAnagraficaInfap generated by hbm2java
 */
public class DAnagraficaInfap implements java.io.Serializable {

	private int codiAnagraficaInfap;
	private int codiArea;
	private int codiApplicazione;
	private int codiFunzione;
	private Set DBusinessServiceses = new HashSet(0);

	public DAnagraficaInfap() {
	}

	public DAnagraficaInfap(int codiAnagraficaInfap, int codiArea,
			int codiApplicazione, int codiFunzione) {
		this.codiAnagraficaInfap = codiAnagraficaInfap;
		this.codiArea = codiArea;
		this.codiApplicazione = codiApplicazione;
		this.codiFunzione = codiFunzione;
	}

	public DAnagraficaInfap(int codiAnagraficaInfap, int codiArea,
			int codiApplicazione, int codiFunzione, Set DBusinessServiceses) {
		this.codiAnagraficaInfap = codiAnagraficaInfap;
		this.codiArea = codiArea;
		this.codiApplicazione = codiApplicazione;
		this.codiFunzione = codiFunzione;
		this.DBusinessServiceses = DBusinessServiceses;
	}

	public int getCodiAnagraficaInfap() {
		return this.codiAnagraficaInfap;
	}

	public void setCodiAnagraficaInfap(int codiAnagraficaInfap) {
		this.codiAnagraficaInfap = codiAnagraficaInfap;
	}

	public int getCodiArea() {
		return this.codiArea;
	}

	public void setCodiArea(int codiArea) {
		this.codiArea = codiArea;
	}

	public int getCodiApplicazione() {
		return this.codiApplicazione;
	}

	public void setCodiApplicazione(int codiApplicazione) {
		this.codiApplicazione = codiApplicazione;
	}

	public int getCodiFunzione() {
		return this.codiFunzione;
	}

	public void setCodiFunzione(int codiFunzione) {
		this.codiFunzione = codiFunzione;
	}

	public Set getDBusinessServiceses() {
		return this.DBusinessServiceses;
	}

	public void setDBusinessServiceses(Set DBusinessServiceses) {
		this.DBusinessServiceses = DBusinessServiceses;
	}

}
