package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:01:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DBusinessServices generated by hbm2java
 */
public class DBusinessServices implements java.io.Serializable {

	private int codiBusinessService;
	private DDipartimenti DDipartimenti;
	private DModelApplicativi DModelApplicativi;
	private String textSiglaBusinessService;
	private String textNomeBusinessService;
	private String descBusinessService;
	private Date dataValiditaInizio;
	private Date dataValiditaFine;
	private String persRespBusinessService;
	private String textUrlBusinessService;
	private Boolean flagConvenzione;
	private String orarLavorativo;
	private Set DAnagraficaInfaps = new HashSet(0);
	private Set DServiziProcessis = new HashSet(0);

	public DBusinessServices() {
	}

	public DBusinessServices(int codiBusinessService,
			DDipartimenti DDipartimenti, DModelApplicativi DModelApplicativi) {
		this.codiBusinessService = codiBusinessService;
		this.DDipartimenti = DDipartimenti;
		this.DModelApplicativi = DModelApplicativi;
	}

	public DBusinessServices(int codiBusinessService,
			DDipartimenti DDipartimenti, DModelApplicativi DModelApplicativi,
			String textSiglaBusinessService, String textNomeBusinessService,
			String descBusinessService, Date dataValiditaInizio,
			Date dataValiditaFine, String persRespBusinessService,
			String textUrlBusinessService, Boolean flagConvenzione,
			String orarLavorativo, Set DAnagraficaInfaps, Set DServiziProcessis) {
		this.codiBusinessService = codiBusinessService;
		this.DDipartimenti = DDipartimenti;
		this.DModelApplicativi = DModelApplicativi;
		this.textSiglaBusinessService = textSiglaBusinessService;
		this.textNomeBusinessService = textNomeBusinessService;
		this.descBusinessService = descBusinessService;
		this.dataValiditaInizio = dataValiditaInizio;
		this.dataValiditaFine = dataValiditaFine;
		this.persRespBusinessService = persRespBusinessService;
		this.textUrlBusinessService = textUrlBusinessService;
		this.flagConvenzione = flagConvenzione;
		this.orarLavorativo = orarLavorativo;
		this.DAnagraficaInfaps = DAnagraficaInfaps;
		this.DServiziProcessis = DServiziProcessis;
	}

	public int getCodiBusinessService() {
		return this.codiBusinessService;
	}

	public void setCodiBusinessService(int codiBusinessService) {
		this.codiBusinessService = codiBusinessService;
	}

	public DDipartimenti getDDipartimenti() {
		return this.DDipartimenti;
	}

	public void setDDipartimenti(DDipartimenti DDipartimenti) {
		this.DDipartimenti = DDipartimenti;
	}

	public DModelApplicativi getDModelApplicativi() {
		return this.DModelApplicativi;
	}

	public void setDModelApplicativi(DModelApplicativi DModelApplicativi) {
		this.DModelApplicativi = DModelApplicativi;
	}

	public String getTextSiglaBusinessService() {
		return this.textSiglaBusinessService;
	}

	public void setTextSiglaBusinessService(String textSiglaBusinessService) {
		this.textSiglaBusinessService = textSiglaBusinessService;
	}

	public String getTextNomeBusinessService() {
		return this.textNomeBusinessService;
	}

	public void setTextNomeBusinessService(String textNomeBusinessService) {
		this.textNomeBusinessService = textNomeBusinessService;
	}

	public String getDescBusinessService() {
		return this.descBusinessService;
	}

	public void setDescBusinessService(String descBusinessService) {
		this.descBusinessService = descBusinessService;
	}

	public Date getDataValiditaInizio() {
		return this.dataValiditaInizio;
	}

	public void setDataValiditaInizio(Date dataValiditaInizio) {
		this.dataValiditaInizio = dataValiditaInizio;
	}

	public Date getDataValiditaFine() {
		return this.dataValiditaFine;
	}

	public void setDataValiditaFine(Date dataValiditaFine) {
		this.dataValiditaFine = dataValiditaFine;
	}

	public String getPersRespBusinessService() {
		return this.persRespBusinessService;
	}

	public void setPersRespBusinessService(String persRespBusinessService) {
		this.persRespBusinessService = persRespBusinessService;
	}

	public String getTextUrlBusinessService() {
		return this.textUrlBusinessService;
	}

	public void setTextUrlBusinessService(String textUrlBusinessService) {
		this.textUrlBusinessService = textUrlBusinessService;
	}

	public Boolean getFlagConvenzione() {
		return this.flagConvenzione;
	}

	public void setFlagConvenzione(Boolean flagConvenzione) {
		this.flagConvenzione = flagConvenzione;
	}

	public String getOrarLavorativo() {
		return this.orarLavorativo;
	}

	public void setOrarLavorativo(String orarLavorativo) {
		this.orarLavorativo = orarLavorativo;
	}

	public Set getDAnagraficaInfaps() {
		return this.DAnagraficaInfaps;
	}

	public void setDAnagraficaInfaps(Set DAnagraficaInfaps) {
		this.DAnagraficaInfaps = DAnagraficaInfaps;
	}

	public Set getDServiziProcessis() {
		return this.DServiziProcessis;
	}

	public void setDServiziProcessis(Set DServiziProcessis) {
		this.DServiziProcessis = DServiziProcessis;
	}

}
