package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:01:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DModelApplicativi generated by hbm2java
 */
public class DModelApplicativi implements java.io.Serializable {

	private int codiModelApplicativo;
	private String descModelApplicativo;
	private Set DBusinessServiceses = new HashSet(0);

	public DModelApplicativi() {
	}

	public DModelApplicativi(int codiModelApplicativo) {
		this.codiModelApplicativo = codiModelApplicativo;
	}

	public DModelApplicativi(int codiModelApplicativo,
			String descModelApplicativo, Set DBusinessServiceses) {
		this.codiModelApplicativo = codiModelApplicativo;
		this.descModelApplicativo = descModelApplicativo;
		this.DBusinessServiceses = DBusinessServiceses;
	}

	public int getCodiModelApplicativo() {
		return this.codiModelApplicativo;
	}

	public void setCodiModelApplicativo(int codiModelApplicativo) {
		this.codiModelApplicativo = codiModelApplicativo;
	}

	public String getDescModelApplicativo() {
		return this.descModelApplicativo;
	}

	public void setDescModelApplicativo(String descModelApplicativo) {
		this.descModelApplicativo = descModelApplicativo;
	}

	public Set getDBusinessServiceses() {
		return this.DBusinessServiceses;
	}

	public void setDBusinessServiceses(Set DBusinessServiceses) {
		this.DBusinessServiceses = DBusinessServiceses;
	}

}
