package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:01:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DProcessi generated by hbm2java
 */
public class DProcessi implements java.io.Serializable {

	private int codiProcesso;
	private String textSiglaProcesso;
	private String descProcesso;
	private Set DServiziProcessis = new HashSet(0);

	public DProcessi() {
	}

	public DProcessi(int codiProcesso) {
		this.codiProcesso = codiProcesso;
	}

	public DProcessi(int codiProcesso, String textSiglaProcesso,
			String descProcesso, Set DServiziProcessis) {
		this.codiProcesso = codiProcesso;
		this.textSiglaProcesso = textSiglaProcesso;
		this.descProcesso = descProcesso;
		this.DServiziProcessis = DServiziProcessis;
	}

	public int getCodiProcesso() {
		return this.codiProcesso;
	}

	public void setCodiProcesso(int codiProcesso) {
		this.codiProcesso = codiProcesso;
	}

	public String getTextSiglaProcesso() {
		return this.textSiglaProcesso;
	}

	public void setTextSiglaProcesso(String textSiglaProcesso) {
		this.textSiglaProcesso = textSiglaProcesso;
	}

	public String getDescProcesso() {
		return this.descProcesso;
	}

	public void setDescProcesso(String descProcesso) {
		this.descProcesso = descProcesso;
	}

	public Set getDServiziProcessis() {
		return this.DServiziProcessis;
	}

	public void setDServiziProcessis(Set DServiziProcessis) {
		this.DServiziProcessis = DServiziProcessis;
	}

}
