package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:01:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * DServiziProcessiId generated by hbm2java
 */
public class DServiziProcessiId implements java.io.Serializable {

	private int codiBusinessService;
	private int codiProcesso;
	private int codiCategoriaMac;
	private int codiCategoriaInf;

	public DServiziProcessiId() {
	}

	public DServiziProcessiId(int codiBusinessService, int codiProcesso,
			int codiCategoriaMac, int codiCategoriaInf) {
		this.codiBusinessService = codiBusinessService;
		this.codiProcesso = codiProcesso;
		this.codiCategoriaMac = codiCategoriaMac;
		this.codiCategoriaInf = codiCategoriaInf;
	}

	public int getCodiBusinessService() {
		return this.codiBusinessService;
	}

	public void setCodiBusinessService(int codiBusinessService) {
		this.codiBusinessService = codiBusinessService;
	}

	public int getCodiProcesso() {
		return this.codiProcesso;
	}

	public void setCodiProcesso(int codiProcesso) {
		this.codiProcesso = codiProcesso;
	}

	public int getCodiCategoriaMac() {
		return this.codiCategoriaMac;
	}

	public void setCodiCategoriaMac(int codiCategoriaMac) {
		this.codiCategoriaMac = codiCategoriaMac;
	}

	public int getCodiCategoriaInf() {
		return this.codiCategoriaInf;
	}

	public void setCodiCategoriaInf(int codiCategoriaInf) {
		this.codiCategoriaInf = codiCategoriaInf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DServiziProcessiId))
			return false;
		DServiziProcessiId castOther = (DServiziProcessiId) other;

		return (this.getCodiBusinessService() == castOther
				.getCodiBusinessService())
				&& (this.getCodiProcesso() == castOther.getCodiProcesso())
				&& (this.getCodiCategoriaMac() == castOther
						.getCodiCategoriaMac())
				&& (this.getCodiCategoriaInf() == castOther
						.getCodiCategoriaInf());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodiBusinessService();
		result = 37 * result + this.getCodiProcesso();
		result = 37 * result + this.getCodiCategoriaMac();
		result = 37 * result + this.getCodiCategoriaInf();
		return result;
	}

}
