package com.ddway.anagraficaBS.model.db;

// Generated Apr 9, 2014 2:50:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DServiziModel generated by hbm2java
 */
public class DServiziModel implements java.io.Serializable {

	private DServiziModelId id;
	private Integer codiModelApplicativo;
	private Date dataFineAssociazione;

	public DServiziModel() {
	}

	public DServiziModel(DServiziModelId id) {
		this.id = id;
	}

	public DServiziModel(DServiziModelId id, Integer codiModelApplicativo,
			Date dataFineAssociazione) {
		this.id = id;
		this.codiModelApplicativo = codiModelApplicativo;
		this.dataFineAssociazione = dataFineAssociazione;
	}

	public DServiziModelId getId() {
		return this.id;
	}

	public void setId(DServiziModelId id) {
		this.id = id;
	}

	public Integer getCodiModelApplicativo() {
		return this.codiModelApplicativo;
	}

	public void setCodiModelApplicativo(Integer codiModelApplicativo) {
		this.codiModelApplicativo = codiModelApplicativo;
	}

	public Date getDataFineAssociazione() {
		return this.dataFineAssociazione;
	}

	public void setDataFineAssociazione(Date dataFineAssociazione) {
		this.dataFineAssociazione = dataFineAssociazione;
	}

}
