package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:04:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * DServiziFunzioni generated by hbm2java
 */
public class DServiziFunzioni implements java.io.Serializable {

	private DServiziFunzioniId id;

	public DServiziFunzioni() {
	}

	public DServiziFunzioni(DServiziFunzioniId id) {
		this.id = id;
	}

	public DServiziFunzioniId getId() {
		return this.id;
	}

	public void setId(DServiziFunzioniId id) {
		this.id = id;
	}

}
