package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:04:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * DServiziFunzioniId generated by hbm2java
 */
public class DServiziFunzioniId implements java.io.Serializable {

	private int codiBusinessService;
	private int codiAnagraficaInfap;

	public DServiziFunzioniId() {
	}

	public DServiziFunzioniId(int codiBusinessService, int codiAnagraficaInfap) {
		this.codiBusinessService = codiBusinessService;
		this.codiAnagraficaInfap = codiAnagraficaInfap;
	}

	public int getCodiBusinessService() {
		return this.codiBusinessService;
	}

	public void setCodiBusinessService(int codiBusinessService) {
		this.codiBusinessService = codiBusinessService;
	}

	public int getCodiAnagraficaInfap() {
		return this.codiAnagraficaInfap;
	}

	public void setCodiAnagraficaInfap(int codiAnagraficaInfap) {
		this.codiAnagraficaInfap = codiAnagraficaInfap;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DServiziFunzioniId))
			return false;
		DServiziFunzioniId castOther = (DServiziFunzioniId) other;

		return (this.getCodiBusinessService() == castOther
				.getCodiBusinessService())
				&& (this.getCodiAnagraficaInfap() == castOther
						.getCodiAnagraficaInfap());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodiBusinessService();
		result = 37 * result + this.getCodiAnagraficaInfap();
		return result;
	}

}
