package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:01:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * DServiziProcessi generated by hbm2java
 */
public class DServiziProcessi implements java.io.Serializable {

	private DServiziProcessiId id;
	private DProcessi DProcessi;
	private DBusinessServices DBusinessServices;
	private Long misuTempoRisoluzioneD;
	private Long misuTempoRisoluzioneH;

	public DServiziProcessi() {
	}

	public DServiziProcessi(DServiziProcessiId id, DProcessi DProcessi,
			DBusinessServices DBusinessServices) {
		this.id = id;
		this.DProcessi = DProcessi;
		this.DBusinessServices = DBusinessServices;
	}

	public DServiziProcessi(DServiziProcessiId id, DProcessi DProcessi,
			DBusinessServices DBusinessServices, Long misuTempoRisoluzioneD,
			Long misuTempoRisoluzioneH) {
		this.id = id;
		this.DProcessi = DProcessi;
		this.DBusinessServices = DBusinessServices;
		this.misuTempoRisoluzioneD = misuTempoRisoluzioneD;
		this.misuTempoRisoluzioneH = misuTempoRisoluzioneH;
	}

	public DServiziProcessiId getId() {
		return this.id;
	}

	public void setId(DServiziProcessiId id) {
		this.id = id;
	}

	public DProcessi getDProcessi() {
		return this.DProcessi;
	}

	public void setDProcessi(DProcessi DProcessi) {
		this.DProcessi = DProcessi;
	}

	public DBusinessServices getDBusinessServices() {
		return this.DBusinessServices;
	}

	public void setDBusinessServices(DBusinessServices DBusinessServices) {
		this.DBusinessServices = DBusinessServices;
	}

	public Long getMisuTempoRisoluzioneD() {
		return this.misuTempoRisoluzioneD;
	}

	public void setMisuTempoRisoluzioneD(Long misuTempoRisoluzioneD) {
		this.misuTempoRisoluzioneD = misuTempoRisoluzioneD;
	}

	public Long getMisuTempoRisoluzioneH() {
		return this.misuTempoRisoluzioneH;
	}

	public void setMisuTempoRisoluzioneH(Long misuTempoRisoluzioneH) {
		this.misuTempoRisoluzioneH = misuTempoRisoluzioneH;
	}

}
