package com.ddway.anagraficaBS.model.db;

// Generated Mar 11, 2014 5:01:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DUtenti generated by hbm2java
 */
public class DUtenti implements java.io.Serializable {

	private int codiUtente;
	private String persNomeUtente;
	private String textPassword;
	private Date dttmUltimoAccesso;

	public DUtenti() {
	}

	public DUtenti(int codiUtente, String persNomeUtente, String textPassword) {
		this.codiUtente = codiUtente;
		this.persNomeUtente = persNomeUtente;
		this.textPassword = textPassword;
	}

	public DUtenti(int codiUtente, String persNomeUtente, String textPassword,
			Date dttmUltimoAccesso) {
		this.codiUtente = codiUtente;
		this.persNomeUtente = persNomeUtente;
		this.textPassword = textPassword;
		this.dttmUltimoAccesso = dttmUltimoAccesso;
	}

	public int getCodiUtente() {
		return this.codiUtente;
	}

	public void setCodiUtente(int codiUtente) {
		this.codiUtente = codiUtente;
	}

	public String getPersNomeUtente() {
		return this.persNomeUtente;
	}

	public void setPersNomeUtente(String persNomeUtente) {
		this.persNomeUtente = persNomeUtente;
	}

	public String getTextPassword() {
		return this.textPassword;
	}

	public void setTextPassword(String textPassword) {
		this.textPassword = textPassword;
	}

	public Date getDttmUltimoAccesso() {
		return this.dttmUltimoAccesso;
	}

	public void setDttmUltimoAccesso(Date dttmUltimoAccesso) {
		this.dttmUltimoAccesso = dttmUltimoAccesso;
	}

}
